### PR TITLE
Strip more fields in PCF

### LINKED ISSUE #159: Comparing schemas can panic in 0.11.0
Here is an example:

```rust
use avro_rs::*;

fn main() {
    let raw_schema = r#"
{
  "type": "record",
  "name": "User",
  "doc": "Hi there.",
  "fields": [
    {"name": "likes_pizza", "type": "boolean", "default": false},
    {"name": "aa-i32",
     "type": {"type": "array", "items": {"type": "array", "items": "int"}},
     "default": [[0], [12, -1]]}
  ]
}
    "#;

    let schema = Schema::parse_str(raw_schema).unwrap();
    let schema2 = schema.clone();

    println!("{:?}", schema == schema2); // this panics
}
```

If I remove `{"name": "likes_pizza", "type": "boolean", "default": false}` then it does not panic.

This is a regression that was likely introduced in `0.11.0` as it still works in `0.10.0`.

### PR DESCRIPTION
**Pull request by lerouxrgd**
Fixes #159

### CODE REVIEW

File: src/schema.rs [hunk 1]
```diff
@@ -818,18 +818,13 @@ fn parsing_canonical_form(schema: &serde_json::Value) -> String {
         serde_json::Value::Object(map) => pcf_map(map),
         serde_json::Value::String(s) => pcf_string(s),
         serde_json::Value::Array(v) => pcf_array(v),
-        serde_json::Value::Number(n) => pcf_number(n),
```
Comment (poros) [inline src/schema.rs:821]: Would you mind explaining why you are removing this line? It isn't immediately clear to me.

File: src/schema.rs [hunk 2]
```diff
@@ -844,7 +839,7 @@ fn pcf_map(schema: &Map<String, serde_json::Value>) -> String {
         }
 
         // Strip out unused fields ([STRIP] rule)
-        if field_ordering_position(k).is_none() {
+        if field_ordering_position(k).is_none() || k == "default" || k == "doc" || k == "aliases" {
```
Comment (poros) [inline src/schema.rs:842]: I know that the spec doesn't mention "default" as field to keep, but I think that changing the default value should actually make a schema different. What do you think?

File: src/rabin.rs [hunk 3]
```diff
@@ -45,8 +45,9 @@ lazy_static! {
 ///
 /// ```rust
 /// use byteorder::{ByteOrder, LittleEndian};
+/// use hex_literal::hex;
 ///
-/// let i = LittleEndian::read_i64(&result.to_vec())
```
Comment (poros) [inline src/rabin.rs:49]: Why this change?

**Review by poros — COMMENTED** [review]
Thanks for contributing! I have read the issue you created, but I am not quite sure I get how all your changes are linked to it. I have marked the points where I would appreciate a couple more words with comments.

File: src/rabin.rs (hunk 3 above)
Comment (poros) [reply src/rabin.rs:49]: Ah, I see now! The test for the docs are broken and I haven't noticed because of https://github.com/rust-lang/cargo/issues/6669. Let me fix the tests first, but feel free to ignore this one.

Comment (poros) [reply src/rabin.rs:49]: I fixed the docs test, please pull master.

File: src/schema.rs (hunk 2 above)
Comment (lerouxrgd) [reply src/schema.rs]: They mention `Strip all others (e.g., doc and aliases)` though. But beyond that, reading data that have been written with some default values isn't related to those values, only to their type. For instance those two schemas should be considered equal:

```
{
    "type": "record",
    "name": "test",
    "fields": [{"name": "a", "type": "long", "default": 42}]
}
```

and

```
{
    "type": "record",
    "name": "test",
    "fields": [{"name": "a", "type": "long", "default": 999}]
}
```

File: src/rabin.rs (hunk 3 above)
Comment (lerouxrgd) [reply src/rabin.rs]: Done

File: src/schema.rs (hunk 1 above)
Comment (lerouxrgd) [reply src/schema.rs:821]: Well as this was used only for default values, if default values are stripped away then this become unnecessary.

File: src/schema.rs (hunk 2 above)
Comment (lerouxrgd) [reply src/schema.rs:842]: It is even worse if one schema specifies `null` as a default value for a complex field (map, array) and another schema doesn't, because they would be exactly the same but their PCF would be different if we consider default value as part of it. And with the current implementation finding `null` (in the default value) just panics.

**Comment by poros** [comment]
I have a problem with the clippy check workflow that I can't figure out atm. I am going to merge the pull request anyway. Thanks for contributing!
